### PR TITLE
Document changes in my_recent_swaps, setprice and orderbook.

### PR DESCRIPTION
**Pull request by artemii235**

### CODE REVIEW

**Comment by artemii235** [comment]
Hi @gcharang! Please publish the changes when this AtomicDEX-API PR is merged: https://github.com/KomodoPlatform/atomicDEX-API/pull/796.

**Comment by gcharang** [comment]
@artemii235 @tonymorony hi! is this PR ready to be merged?

**Comment by artemii235** [comment]
@gcharang Yes, please publish the changes on the website.

**Comment by gcharang** [comment]
thanks!

**Pull request merged**
