### PR TITLE
Update lightning methods in postman collection, add a use case

### PR DESCRIPTION
**Pull request by shamardy**

### CODE REVIEW

**Comment by shamardy** [comment]
Let's leave this PR open until this https://github.com/KomodoPlatform/atomicDEX-API/pull/1513 is merged. I will update the collection one last time after the task manager PR is merged :)

**Comment by shamardy** [comment]
@gcharang @smk762 This is ready for review as this [PR](https://github.com/KomodoPlatform/atomicDEX-API/pull/1513) is merged

**Comment by shamardy** [comment]
> the actual userpass of your environment was committed instead of \"{{userpass}}\" (around 38 cases)

This is intentional. The use cases are supposed to be tried between the 2 playground nodes :)

**Comment by shamardy** [comment]
> The use cases are supposed to be tried between the 2 playground nodes :)

They should also be used in order, to try out starting a lightning node, connecting to other lightning nodes, opening channels, sending payments and doing swaps.

**Review by gcharang — APPROVED** [review]

**Review by smk762 — APPROVED** [review]

**Pull request merged**
