### PR TITLE
MmRPC Protocol v2.0

### PR DESCRIPTION
**Pull request by sergeyboyko0791**
* Add 'trade_preimage' and 'withdraw' RPC functions to the 'AtomicDEX API 2.0' section
* Up-to-date the 'trade_preimage' examples (add 'paid_from_trading_vol', add 'required_balance' to 'total_fees')

### CODE REVIEW

**Review by artemii235 — APPROVED** [review]
Thanks for the PR! :fire:

**Comment by sergeyboyko0791** [comment]
@yurii-khi @Milerius please note that there are error types like
```
#### Transport

| Structure | Type   | Description                     |
| --------- | ------ | ------------------------------- |
| (none)    | string | the transport error description |
```

It means that the `error_data` will be a string instead of a JSON object. This is done for convenience on the mm2 side.

An example of a common error, where the `error_data` is a JSON object:
```json
{
  "mmrpc": "2.0",
  "error":"The volume 0.00001 of the RICK coin less than minimum transaction amount 0.0001",
  "error_path": "maker_swap",
  "error_trace": "maker_swap:1599]",
  "error_type": "VolumeTooLow",
  "error_data": {
    "coin": "RICK",
    "volume": "0.00001",
    "threshold": "0.0001"
  },
  "id": 0
}
```

An example of an error, where the `error_data` is a string:
```json
{
  "mmrpc": "2.0",
  "error": "Transport error: JsonRpcError { client_info: 'coin: tBTC', request: JsonRpcRequest { jsonrpc: '2.0', id: '31', method: 'blockchain.estimatefee', params: [Number(1), String('ECONOMICAL')] }, error: Transport('rpc_clients:1237] rpc_clients:1239] ['rpc_clients:2047] common:1385] future timed out']') }",
  "error_path": "taker_swap.utxo_common",
  "error_trace": "taker_swap:1599] utxo_common:1990] utxo_common:166]",
  "error_type": "Transport",
  "error_data": "JsonRpcError { client_info: 'coin: tBTC', request: JsonRpcRequest { jsonrpc: '2.0', id: '31', method: 'blockchain.estimatefee', params: [Number(1), String('ECONOMICAL')] }, error: Transport('rpc_clients:1237] rpc_clients:1239] ['rpc_clients:2047] common:1385] future timed out']') }",
  "id": 0
}
```

Would it be ok on GUI side?

**Comment by gcharang** [comment]
@sergeyboyko0791 thanks! LGTM. can merge if latest mm2 release has these RPC

**Comment by artemii235** [comment]
@gcharang We will release them this week, I will ping you once done :slightly_smiling_face:

**Pull request merged**
