### PR TITLE
Add QRC20 Native mode support

### PR DESCRIPTION
**Pull request by sergeyboyko0791**
Related to https://github.com/KomodoPlatform/atomicDEX-API/pull/779
Add examples to QRC20 withdraw https://github.com/KomodoPlatform/atomicDEX-API/issues/759
Add the `get_trade_fee` tip for QRC20 token https://github.com/KomodoPlatform/atomicDEX-API/issues/763

### CODE REVIEW

**Comment by sergeyboyko0791** [comment]
Hi @gcharang
Could you please review and merge the changes after the https://github.com/KomodoPlatform/atomicDEX-API/pull/779 is merged into mm2.1?

**Comment by gcharang** [comment]
thanks! will do

**Comment by sergeyboyko0791** [comment]
Hi @gcharang, the branch mentioned above has been merged. Could you please merge the `sidd` into master?

**Comment by gcharang** [comment]
thanks! will do!

**Pull request merged**
