### PR TITLE
Update `trade_preimage` RPC call

### PR DESCRIPTION
**Pull request by sergeyboyko0791**
* Add the `ExtendedFeeInfo` structure
* Add the price field to the trade_preimage RPC request
* Add the result.total_fees field to the trade_preimage RPC response
* Add the result.taker_fee.coin filed

### CODE REVIEW

**Comment by sergeyboyko0791** [comment]
@Milerius @artemii235 @yurii-khi could you please take a quick look at the protocol changes?

**Comment by sergeyboyko0791** [comment]
This PR is related to [these changes](https://github.com/KomodoPlatform/atomicDEX-API/pull/869)

**Review by artemii235 — CHANGES_REQUESTED** [review]
Thanks for the PR! Please move the `trade_preimage` so it is alphabetically ordered like all other methods are.

**Comment by sergeyboyko0791** [comment]
Done
> Thanks for the PR! Please move the trade_preimage so it is alphabetically ordered like all other methods are.

**Review by artemii235 — APPROVED** [review]
LGTM

**Pull request merged**
