### PR TITLE
WIP Update docs according to the qrc20_swap branch

### PR DESCRIPTION
**Pull request by sergeyboyko0791**

### CODE REVIEW

**Comment by sergeyboyko0791** [comment]
Linked issues: [#735](https://github.com/KomodoPlatform/atomicDEX-API/pull/735)
@artemii235 could you please review the changes

**Review by artemii235 — APPROVED** [review]
LGTM, thanks!

**Comment by artemii235** [comment]
@gcharang Hi! Please publish this PR changes after https://github.com/KomodoPlatform/atomicDEX-API/pull/735 is merged.

**Comment by gcharang** [comment]
> @gcharang Hi! Please publish this PR changes after [KomodoPlatform/atomicDEX-API#735](https://github.com/KomodoPlatform/atomicDEX-API/pull/735) is merged.

yup, will do!

**Pull request merged**
